name: police_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  sidebarx: ^0.16.2
  http: ^1.2.1
  provider: ^6.1.2

  cupertino_icons: ^1.0.6
  email_validator: ^2.1.17
  intl: ^0.19.0
  emoji_picker_flutter: ^1.6.4
  image_picker: ^0.8.6
  video_player: ^2.2.18
  file_picker: ^5.2.2
  geolocator: ^8.0.0
  google_maps_flutter: ^2.0.6

  

dependency_overrides:
    intl: ^0.17.0


dev_dependencies: 
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/